pipeline {
    agent {
        label "slave1"
    }
    options {
        gitLabConnection('gitlab-connection')
        gitlabBuilds(builds: ['Build', 'Deploy'])
    }

    stages {
        stage("Android build") {
            when{
                branch 'master';
            }
            steps{
                updateGitlabCommitStatus name: 'Android build', state: 'running'
                build(
                    job: "POD-Android-pipeline", 
                    parameters: [string(name:"BRANCH_NAME", value:"${env.BRANCH_NAME}")]
                )
            }
            post {
                failure {
                    updateGitlabCommitStatus name: 'Android build', state: 'failed'
                }
                success {
                    updateGitlabCommitStatus name: 'Android build', state: 'success'
                }
                aborted {
                    updateGitlabCommitStatus name: 'Android build', state: 'canceled'
                }
            }
        }
    }
}
