FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles

VOLUME /tmp

COPY $BIN_BASE/maryfarm-apigateway-service-0.0.1-SNAPSHOT.jar ApiGateway.jar

ENTRYPOINT [ "java", "-jar", "ApiGateway.jar", "--spring.profiles.active=prod"]
# CMD ["java","-Dspring.profiles.active=prod","/home/maryfarm-config-service-0.0.1-SNAPSHOT.jar"]

# docker build -f Dockerfile_apigateway --tag MaryFarm/apigateway-service:1.0 .
# docker push MaryFarm/apigateway-service:1.0

# docker run -d -p 8000:8000 --network myfarm-network \
#  -e "spring.cloud.config.uri=http://config-service:8888" \
#  -e "spring.rabbitmq.host=rabbitmq" \
#  -e "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/" \
#  --name apigateway-service MaryFarm/apigateway-service:1.0