FROM mysql
LABEL org.opencontainers.image.authors="isakggong@gmail.com"
ENV MYSQL_ROOT_PASSWORD 1234
ENV MYSQL_DATABASE farm
EXPOSE 3306

ENTRYPOINT ["mysqld", "--user=root"]

# docker build -f Dockerfile_mysql --tag MaryFarm/mysql:1.0 .
# docker push MaryFarm/mysql:1.0
# docker run -d -p 3307:3306 --network maryfarm-network --name mysqldb MaryFarm/mysql:1.0 

# docker exec -it mysqldb /bin/bash
# mysql -h127.0.0.1 -uroot -p
# mysql -hlocalhost -uroot -p

# 권한을 허용하고자 하는 DB에 가서
# CREATE USER 'root'@'*' IDENTIFIED BY'1234';
# grant all privileges on *.* to 'root'@'%' ;
# *.* 모든 데이터베이스의 권한
# 'root' 계정으로 '%' ip 주소는 모두 허용한다.

# flush privileges; 작업 내용을 반영함.

# docker network inspect maryfarm-network



