FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles

VOLUME /tmp

COPY $BIN_BASE/maryfarm-discovery-service-0.0.1-SNAPSHOT.jar DiscoveryService.jar

ENTRYPOINT [ "java", "-jar", "DiscoveryService.jar", "--spring.profiles.active=prod"]
# CMD ["java","-Dspring.profiles.active=prod","/home/maryfarm-config-service-0.0.1-SNAPSHOT.jar"]

# docker build -f Dockerfile_discovery --tag MaryFarm/discovery-service:1.0 .
# docker push MaryFarm/discovery-service:1.0

# docker run -d -p 8761:8761 --network ecommerce-network \

#  -e "spring.cloud.config.uri=http://config-service:8888" \

#  --name discovery-service edowon0623/discovery-service:1.0