FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles
VOLUME /tmp

COPY $BIN_BASE/maryfarm-config-service-0.0.1-SNAPSHOT.jar ConfigService.jar

ENTRYPOINT [ "java", "-jar", "ConfigService.jar", "--spring.profiles.active=prod"]
# CMD ["java","-Dspring.profiles.active=prod","/home/maryfarm-config-service-0.0.1-SNAPSHOT.jar"]

# docker build -f Dockerfile_discovery --tag MaryFarm/discovery-service:1.0 .
# docker push MaryFarm/discovery-service:1.0

# docker run -d -p 8888:8888 --network maryfarm-network \
#  -e "spring.rabbitmq.host=rabbitmq" \
#  -e "spring.profiles.active=prod" \
#   --name config-service isakggong/config-server:maryfarm-1.0