FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles

VOLUME /tmp

COPY $BIN_BASE/maryfarm-plant-service-0.0.1-SNAPSHOT.jar PlantService.jar

ENTRYPOINT [ "java", "-jar", "PlantService.jar", "--spring.profiles.active=prod"]
# CMD ["java","-Dspring.profiles.active=prod","/home/maryfarm-config-service-0.0.1-SNAPSHOT.jar"]

# docker build -f Dockerfile_plant --tag MaryFarm/plant-service:1.0 .
# docker push MaryFarm/plant-service:1.0

# docker run -d --network ecommerce-network \
#  --name plant-service \
#  -e "spring.cloud.config.uri=http://config-service:8888" \
#  -e "spring.rabbitmq.host=rabbitmq" \
#  -e "spring.zipkin.base-url=http://zipkin:9411" \
#  -e "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/" \
#  -e "spring.datasource.url=jdbc:mysqldb://mysqldb:3306/farm" \
#  -e "logging.file=/api-logs/plants-ws.log" \
#  MaryFarm/plant-service:1.0