FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles
VOLUME /tmp

COPY $BIN_BASE/maryfarm-user-service-0.0.1-SNAPSHOT.jar UserService.jar

ENTRYPOINT [ "java", "-jar", "UserService.jar", "--spring.profiles.active=prod"]
# CMD ["java","-Dspring.profiles.active=prod","/home/maryfarm-config-service-0.0.1-SNAPSHOT.jar"]

# docker build -f Dockerfile_user --tag MaryFarm/user-service:1.0 .
# docker push MaryFarm/user-service:1.0

# docker run -d --network ecommerce-network \
#  --name user-service \
#  -e "spring.cloud.config.uri=http://config-service:8888" \
#  -e "spring.rabbitmq.host=rabbitmq" \
#  -e "spring.zipkin.base-url=http://zipkin:9411" \
#  -e "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/" \
#  -e "logging.file=/api-logs/users-ws.log" \
#  MaryFarm/user-service:1.0